"""empty message

Revision ID: 0b62ed3b7519
Revises: 
Create Date: 2018-01-23 19:39:39.797000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b62ed3b7519'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drugType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.String(length=500), nullable=False),
    sa.Column('isSale', sa.Boolean(), nullable=False),
    sa.Column('stockDate', sa.Date(), nullable=True),
    sa.Column('saleDate', sa.Date(), nullable=True),
    sa.Column('stockPrice', sa.REAL(), nullable=True),
    sa.Column('salePice', sa.REAL(), nullable=True),
    sa.Column('drugTypeId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drugTypeId'], ['drugType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'user', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('content', mysql.VARCHAR(length=200), nullable=True))
    op.drop_table('drug')
    op.drop_table('drugType')
    # ### end Alembic commands ###
