"""initial migration

Revision ID: 9de619369477
Revises: 
Create Date: 2018-01-23 17:01:47.171000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9de619369477'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DrugType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telephone', sa.String(length=11), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Drug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.String(length=500), nullable=False),
    sa.Column('isSale', sa.Boolean(), nullable=False),
    sa.Column('stockDate', sa.Date(), nullable=True),
    sa.Column('saleDate', sa.Date(), nullable=True),
    sa.Column('stockPrice', sa.REAL(), nullable=True),
    sa.Column('salePice', sa.REAL(), nullable=True),
    sa.Column('drugTypeId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drugTypeId'], ['DrugType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('Drug')
    op.drop_table('User')
    op.drop_table('DrugType')
    # ### end Alembic commands ###
